name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # Permite executar o workflow manualmente

env:
  AZURE_RESOURCE_GROUP: whitelabel-rg
  AZURE_CONTAINER_APP_NAME: whitelabel-app
  # O endereço completo do ACR (login server)
  CONTAINER_REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  DOCKER_IMAGE_NAME: whitelabel
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # Removido o login na Azure, mantendo apenas login no ACR
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }},${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          
      # Etapa de deploy removida - será feito manualmente pelo portal Azure
      # Para fazer deploy manualmente:
      # 1. Vá para o Container App no portal Azure
      # 2. Clique em "Revisions" e depois "Create new revision"
      # 3. Selecione a nova imagem: ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
      # 4. Configure as variáveis de ambiente necessárias
      # 5. Crie a revisão