name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main  # ou 'master', se for o nome do seu branch principal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login no Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 3️⃣ Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/locadora-crud:latest .

      # 4️⃣ Push da imagem pro ACR
      - name: Push image to Azure Container Registry
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/locadora-crud:latest
