name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches:
      - main

env:
  ACR_NAME: acrlocadora           # nome do seu Azure Container Registry (sem .azurecr.io)
  IMAGE_NAME: locadora-crud

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login no Azure Container Registry
        run: |
          az acr login --name $ACR_NAME

      - name: Build da imagem Docker
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .

      - name: Push da imagem pro ACR
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest
