name: Trigger auto deployment for testeapp
# DESATIVADO - usando azure-deploy.yml em vez deste workflow

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ disabled-main ]
    paths:
    - '**'
    - '.github/workflows/testeapp-AutoDeployTrigger-fae08d6f-62d9-4439-9982-7e6bf09088f9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESTEAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTEAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTEAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.TESTEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTEAPP_REGISTRY_PASSWORD }}
          containerAppName: testeapp
          resourceGroup: teste
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


